# Generated by Django 5.0.7 on 2024-07-20 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_bus_bus_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_passengers', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.stop')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('seat_block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.seatblock')),
            ],
        ),
    ]
