# Generated by Django 5.0.7 on 2024-07-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_seatblock_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seatblock',
            name='block_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, null=True, unique=True),
        ),
    ]
